### ISSUE TITLE
Right pane shrinks when switching tabs

### ISSUE THREAD

**Issue by AnyOldName3** [apitrace/apitrace#621] opened 2019-06-21 13:51 UTC
In QAPITrace, I usually make the right pane (Parameters, Shaders, Uniforms etc.) wider so I can actually see what it's displaying. Recently, it's started resetting to the default width when I change tabs.

I first noticed this in a Windows nightly from January, and it's still present in a nightly from today. I haven't tested this on other platforms, and haven't tested older builds except one from a couple of years ago which didn't have the issue.

**Comment by jrfonseca** [comment] 2019-06-22 06:28
Yes, it drives me nuts too.   I don't know how it started or how to fix it.  It only happens on Windows -- not on Linux.  So I suspect it was an upstream Qt change.

@zackr Do you happen to know what could be the cause/fix?

**Comment by zackr** [comment] 2019-06-27 15:34
I saw that too, but I just updated locally to Qt 5.13.0 on windows, compiled qapitrace and it's working fine. It looks like it was some Qt bug. Could you double check whether you still see it with 5.13.0?

**Comment by jrfonseca** [comment] 2019-06-28 12:11
Thanks Zack. You're right, upgrading from Qt 5.11 to Qt 5.13 fixed the issue.  I'll upgrade the Qt on the Jenkins server that's building the binaries.

**Comment by jrfonseca** [comment] 2019-06-28 13:08
It's now fixed on the latest binaries.

**Closed by jrfonseca** 2019-06-28 13:08 UTC
Labels: GUI
