### ISSUE TITLE
SEGFAULT after trace replay

### ISSUE THREAD

**Issue by computerquip** [apitrace/apitrace#364] opened 2015-07-21 23:02 UTC
If I attempt to replay the trace below via qapitrace, the application segfaults. Below is an archive that contains both the core dump and trace that caused said coredump. 

I'm running Arch Linux with apitrace32/apitrace from the master branch. 
I don't think it's the issue but I also have a GTX 770 with proprietary drivers (352.21).

https://drive.google.com/file/d/0B5DdvdCeuzcDT2NvYm9VcjdrZGs/view?usp=sharing

**Comment by jrfonseca** [comment] 2015-07-22 18:11
I can't use the core as I don't have the symbols.  Can you get a stack back trace from that core with gdb?

**Comment by jrfonseca** [comment] 2015-07-22 18:20
It might be a duplicate of issue #357.  You should also retry with 1b587ca868ee75758959c2470a9c35a21299377f.

**Comment by jrfonseca** [comment] 2015-08-03 10:35
I'm afraid there's not enough info for me to dig deeper.  I can't repro and I get symbol names from the core. If the issue persists and you can provide a stack back trace then feel free to reopen.

**Closed by jrfonseca** 2015-08-03 10:35 UTC
Labels: GUI
