### ISSUE TITLE
AutoMoc: Error: moc predefs generation command failed

### ISSUE THREAD

**Issue by ishitatsuyuki** [apitrace/apitrace#528] opened 2017-08-31 00:22 UTC
https://github.com/apitrace/apitrace/blob/65d2605/gui/CMakeLists.txt#L74

```
Generating MOC predefs moc_predefs.h
AutoMoc: Error: moc predefs generation command failed
AutoMoc: Command:
/usr/bin/c++ -dM -E -c /usr/share/cmake-3.9/Modules/CMakeCXXCompilerABI.cpp -I/tmp/tmp.cU62V3fLK5/src/apitrace-7.1/build/gui -I/tmp/tmp.cU62V3fLK5/src/apitrace-7.1/gui -I/tmp/tmp.cU62V3fLK5/src/apitrace-7.1/build/gui/qapitrace_autogen/include -I/tmp/tmp.cU62V3fLK5/src/apitrace-7.1/thirdparty/khronos -I/tmp/tmp.cU62V3fLK5/src/apitrace-7.1/thirdparty/snappy -I/tmp/tmp.cU62V3fLK5/src/apitrace-7.1/thirdparty/libbacktrace -I/tmp/tmp.cU62V3fLK5/src/apitrace-7.1/thirdparty/gtest/include -I/tmp/tmp.cU62V3fLK5/src/apitrace-7.1/common -I/tmp/tmp.cU62V3fLK5/src/apitrace-7.1 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/lib/qt/mkspecs/linux-g++ -I/usr/include/qt/QtWebKitWidgets -I/usr/include/qt/QtWebKit -I/usr/include/qt/QtNetwork -I/usr/include -DHAVE_BACKTRACE=1 -DHAVE_READPROC_H -DHAVE_X11 -DQT_CORE_LIB -DQT_FORCE_ASSERTS -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_WEBKITWIDGETS_LIB -DQT_WEBKIT_LIB -DQT_WIDGETS_LIB -D_GNU_SOURCE -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -nn
AutoMoc: Command output:
c++: error: unrecognized command line option ‘-nn’; did you mean ‘-Qn’?
```

GCC 7.2.0, Qt 5.9.1

**Comment by vitlav** [comment] 2017-10-24 07:05
It is error with compiler command line forming. cmake put CMAKE_AUTOMOC_MOC_OPTIONS to compiler options instead moc options.
Have you any fixes?

**Comment by EoD** [comment] 2017-10-25 12:55
I am unable to reproduce this, even when trying to use a similar setup as described in https://bugs.gentoo.org/634292

The line you are pointing out in the ``CMakeLists.txt`` file are from commit f46f1e37f4e79eb3095933e7fa44eb7ad7401944 which is more than 2 years old.

It would be helpful if you could provide further information:

* Is this a regression with CMake 3.9? Does it build with CMake 3.8?
* What kind of parameters are you using for cmake?

**Comment by ishitatsuyuki** [comment] 2017-10-25 12:57
I was building on Arch at the exact time I opened this issue. I don't have a computer now, so I have no idea if this is still the case. IIRC I was just building without parameters, if not I may be building the AUR -git version.

**Comment by parkerlreed** [comment] 2017-10-27 22:12
Running into this just trying to build from repo directly (Also on Arch Linux)

cmake 3.9.4-1
qt5-base 5.9.2-1
gcc 7.2.0-3

````
git clone
$ cd apitrace
$ mkdir build/ && cd build/
$ cmake .. -Bbuild -DCMAKE_INSTALL_PREFIX=/usr -DPYTHON_EXECUTABLE=/usr/bin/python2.7 -DENABLE_GUI=TRUE
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test HAVE_COMPILER_TLS
-- Performing Test HAVE_COMPILER_TLS - Success
-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.14", minimum required is "2.7") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found procps: /usr/lib/libprocps.so  
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/libX11.so
-- Performing Test CXX_COMPILER_FLAG_VISIBILITY
-- Performing Test CXX_COMPILER_FLAG_VISIBILITY - Success
-- Performing Test CXX_COMPILER_FLAG_STD_GNUXX11
-- Performing Test CXX_COMPILER_FLAG_STD_GNUXX11 - Success
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Using bundled SNAPPY
-- Found ZLIB: /usr/lib/libz.so (found suitable version "1.2.11", minimum required is "1.2.6") 
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.11") 
-- Found PNG: /usr/lib/libpng.so (found version "1.6.34") 
-- Looking for _Unwind_Backtrace
-- Looking for _Unwind_Backtrace - found
-- Looking for _Unwind_GetIPInfo
-- Looking for _Unwind_GetIPInfo - found
-- Performing Test FLAG_UNWIND_TABLES
-- Performing Test FLAG_UNWIND_TABLES - Success
-- Performing Test HAVE_SYNC_FUNCTIONS
-- Performing Test HAVE_SYNC_FUNCTIONS - Success
-- Performing Test HAVE_ATOMIC_FUNCTIONS
-- Performing Test HAVE_ATOMIC_FUNCTIONS - Success
-- Looking for mmap
-- Looking for mmap - found
-- Looking for MAP_ANONYMOUS
-- Looking for MAP_ANONYMOUS - found
-- Looking for MAP_ANON
-- Looking for MAP_ANON - found
-- Looking for dl_iterate_phdr
-- Looking for dl_iterate_phdr - found
-- Looking for fcntl
-- Looking for fcntl - found
-- Looking for strnlen
-- Looking for strnlen - found
-- Looking for getexecname
-- Looking for getexecname - not found
-- Looking for dwarf.h
-- Looking for dwarf.h - found
-- Looking for libdwarf/dwarf.h
-- Looking for libdwarf/dwarf.h - not found
-- Performing Test STATIC_LIBSTDCXX_PIC
-- Performing Test STATIC_LIBSTDCXX_PIC - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/parker/build/apitrace/build/build
$ make -j5 -C build
...
Generating MOC predefs moc_predefs.h
AutoMoc: Error: moc predefs generation command failed
AutoMoc: Command:
/usr/bin/c++ -dM -E -c /usr/share/cmake-3.9/Modules/CMakeCXXCompilerABI.cpp -I/home/parker/build/apitrace/build/build/gui -I/home/parker/build/apitrace/gui -I/home/parker/build/apitrace/build/build/gui/qapitrace_autogen/include -I/home/parker/build/apitrace/thirdparty/khronos -I/home/parker/build/apitrace/compat -I/home/parker/build/apitrace/thirdparty/snappy -I/home/parker/build/apitrace/thirdparty/libbacktrace -I/home/parker/build/apitrace/thirdparty/gtest/include -I/home/parker/build/apitrace/lib/trace -I/home/parker/build/apitrace/lib/os -I/home/parker/build/apitrace/lib/image -I/home/parker/build/apitrace/lib/ubjson -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/lib/qt/mkspecs/linux-g++ -I/usr/include/qt/QtNetwork -I/usr/include -DHAVE_BACKTRACE=1 -DHAVE_READPROC_H -DHAVE_X11 -DQT_CORE_LIB -DQT_FORCE_ASSERTS -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -D_GNU_SOURCE -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -nn
AutoMoc: Command output:
c++: error: unrecognized command line option ‘-nn’; did you mean ‘-Qn’?


make[2]: *** [gui/CMakeFiles/qapitrace_autogen.dir/build.make:69: gui/CMakeFiles/qapitrace_autogen] Error 1
make[2]: Leaving directory '/home/parker/build/apitrace/build/build'
make[1]: *** [CMakeFiles/Makefile2:1810: gui/CMakeFiles/qapitrace_autogen.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
...
````

**Comment by vitlav** [comment] 2017-10-28 07:49
It is a bug since cmake 3.9.2
Please report it to
https://gitlab.kitware.com/cmake/cmake/issues

**Comment by EoD** [comment] 2017-10-30 15:18
@vitlav Why do you think this? It does work for me with CMake 3.9.4, so I don't think reporting it will help.

**Comment by vitlav** [comment] 2017-10-30 15:26
I have tested it:
AutoMoc: Error: moc predefs generation command failed
AutoMoc: Command:
/usr/bin/c++ -dM -E -c /usr/share/cmake/Modules/CMakeCXXCompilerABI.cpp -I/home/lav/Projects/git-alt/TODO/apitrace.git/gui -I/home/lav/Projects/git-alt/TODO/apitrace.git/gui/qapitrace_autogen/include -I/home/lav/Projects/git-alt/TODO/apitrace.git/thirdparty/khronos -I/home/lav/Projects/git-alt/TODO/apitrace.git/compat -I/home/lav/Projects/git-alt/TODO/apitrace.git/thirdparty/snappy -I/home/lav/Projects/git-alt/TODO/apitrace.git/thirdparty/libbacktrace -I/home/lav/Projects/git-alt/TODO/apitrace.git/thirdparty/gtest/include -I/home/lav/Projects/git-alt/TODO/apitrace.git/lib/trace -I/home/lav/Projects/git-alt/TODO/apitrace.git/lib/os -I/home/lav/Projects/git-alt/TODO/apitrace.git/lib/image -I/home/lav/Projects/git-alt/TODO/apitrace.git/lib/ubjson -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/share/qt5/../../lib64/qt5/mkspecs/linux-g++ -I/usr/include/qt5/QtNetwork -I/usr/include -DHAVE_BACKTRACE=1 -DHAVE_X11 -DQT_CORE_LIB -DQT_FORCE_ASSERTS -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -D_GNU_SOURCE -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -nn
AutoMoc: Command output:
x86_64-alt-linux-g++: error: unrecognized command line option ‘-nn’; did you mean ‘-Qn’?

$ cmake --version
cmake version 3.9.2

$ git log HEAD | head
commit 7c76b9014db03f7ad17bff9d3cb476d13e2baa8a
Author: Jose Fonseca <jfonseca@vmware.com>
Date:   Mon Oct 9 18:00:42 2017 +0100

    dxgitrace: Support undocumented use counted interfaces.

**Comment by vitlav** [comment] 2017-10-30 15:31
I guess it was fixed with this commit:
commit d0f1581719644cc9b40a3ad4425bd37369f11c7e
Author: Sebastian Holtermann <sebholt@xwmw.org>
Date:   Wed Sep 13 16:08:48 2017 +0200

    Autogen: Backport autogen target dependency as file dependency fix
    
    Target dependencies of the origin target were mistakenly forwarded to
    the _autogen target as *file* dependencies.  This patch introduces
    proper distinction between *target* and *file* dependencies of the
    _autogen target.
    
    This patch also changes when PRE_BUILD is used for AUTOGEN in the Visual
    Studio generator. Formerly PRE_BUILD was disabled when the origin target
    depended on *any* other target. Now PRE_BUILD is only disabled if a
    dependency of the _autogen target to an additional *file* is detected.
    
    Fixes: #17278, #17205

**Comment by vitlav** [comment] 2017-10-30 15:38
The patch I found in Fedora's apitrace package:
diff -rupN apitrace-7.1/gui/CMakeLists.txt apitrace-7.1-new/gui/CMakeLists.txt
--- apitrace-7.1/gui/CMakeLists.txt<--->2015-11-23 23:19:57.000000000 +0100
+++ apitrace-7.1-new/gui/CMakeLists.txt>2017-08-07 18:50:40.782451889 +0200
@@ -80,8 +80,6 @@ set(qapitrace_UIS
    )
.
 set (CMAKE_AUTOMOC ON)
-# Silence `Note: No relevant classes found. No output generated.`
-set (CMAKE_AUTOMOC_MOC_OPTIONS "-nn")

They use cmake-3.9.3-1.fc28.src.rpm with the bug.

**Comment by vitlav** [comment] 2017-10-30 17:05
I just checked latest apitrace with
$ cmake --version
cmake version 3.9.4

 x86_64-alt-linux-g++: error: unrecognized command line option '-nn'; did you mean '-Qn'?

**Comment by EoD** [comment] 2017-10-30 17:13
@vitlav the error is already known (see links of gentoo/debian bugreports) 
@vitlav your suggested CMake commit fix, is not related to the problem at all.
@vitlav the patch you suggested is **not valid**.
@vitlav thanks for the last reply. You confirmed, that the problem is not related to CMake 3.9 as we suggested above as well. I can also confirm that downgrading to CMake 3.9.2 does not produce an error on my side.

If possible, please try to answer the question of [my post above](https://github.com/apitrace/apitrace/issues/528#issuecomment-339320508).

**Comment by vitlav** [comment] 2017-10-30 19:54
@EoD, I have the same problem with other application (telegram-desktop), so it is cmake related problem.
@EoD, I just checked against qt 5.7.1 and cmake 3.9.2. Build done.
As result, the problem in qt 5.9 + cmake >= 3.9

**Comment by vitlav** [comment] 2017-10-30 20:11
Fedora's maintainer hack:
http://pkgs.fedoraproject.org/cgit/rpms/apitrace.git/commit/?id=114ea92b37b21a54bbf42aca48b35143c75eb16c

**Comment by EoD** [comment] 2017-10-31 10:04
@vitlav Nice, so it is indeed Qt 5.9! 

Are you sure that Qt 5.9 + CMake 3.8 does build fine? I would expect it to fail as well.

**Comment by vitlav** [comment] 2017-10-31 10:35
@EoD 
I just checked with cmake 3.6.3 and qt 5.9.2. Build done.
Sorry, I can't check with cmake 3.8

**Comment by EoD** [comment] 2017-10-31 12:46
@vitlav You were right, it only happens with the exact combination of CMake 3.9 + Qt 5.9.

I opened a bug report at CMake in order to get some upstream feedback: https://gitlab.kitware.com/cmake/cmake/issues/17418

**Comment by vitlav** [comment] 2017-10-31 13:22
@EoD, thank you for the report!

-- 
С уважением,
Виталий Липатов,
Etersoft

**Comment by EoD** [comment] 2017-10-31 13:27
It has been confirmed upstream. It is a Cmake bug and will be addressed in https://gitlab.kitware.com/cmake/cmake/merge_requests/1432

@jrfonseca Could you add the appropriate labels for this bug? Something like NOTOURBUG.

**Comment by EoD** [comment] 2017-11-03 15:37
@ishitatsuyuki @vitlav @parkerlreed 
A new version of CMake is available which fixes the issue described here: https://cmake.org/files/v3.9/

Please consider closing the bug.

**Comment by jrfonseca** [comment] 2017-11-08 14:04
Thanks for looking into this and following up upstream.  Closing now.

**Closed by jrfonseca** 2017-11-08 14:04 UTC
Labels: 3rd Party, Build
