### ISSUE TITLE
Screenshots are vertically inverted when using eglretrace on Waffle

### ISSUE THREAD

**Issue by linkmauve** [apitrace/apitrace#389] opened 2015-09-18 15:53 UTC
When dumping a screenshot using `eglretrace -s img_ some_apitrace.trace` with WAFFLE_PLATFORM being one of glx, x11_egl or wayland, the screenshot is vertically inverted, as if it was dumped without the GL_MESA_pack_invert extension (or similar post-treatment).

**Comment by jrfonseca** [comment] 2015-09-18 18:01
I can't repro this here.

I tried with a trace of a trivial triangle ( https://github.com/apitrace/apitrace-tests/blob/master/apps/egl/gles2/tri_glsl.cpp ), both glx and x11_egl,  and snapshots are upright.

**Comment by jrfonseca** [comment] 2015-10-29 21:53
I'm closing this issue since I couldn't reproduce it.  If it persists, please reopen and provide a test trace.

**Closed by jrfonseca** 2015-10-29 21:53 UTC
Labels: Replaying
