### ISSUE TITLE
Apitrace should support querying core functions with eglGetProcAddress on platforms that support that such as Mesa

### ISSUE THREAD

**Issue by sstewartgallus** [apitrace/apitrace#301] opened 2014-12-06 17:26 UTC
After I converted my GUI to not link directly with the OpenGL ES
library on my system and instead only fetch function pointers via
`eglGetProcAddress` retracing traces of my application stopped working
and started crashing with segmentation faults.

Platform details:

~~~
$ uname -a
Linux proteus 3.17.4-gnu #1 SMP Sat Nov 22 06:12:03 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
~~~

~~~
$ es2_info
libEGL warning: failed to create a pipe screen for i965
EGL_VERSION: 1.4 (DRI2)
EGL_VENDOR: Mesa Project
EGL_EXTENSIONS:
    EGL_MESA_drm_image, EGL_WL_bind_wayland_display, EGL_KHR_image_base, 
    EGL_KHR_image_pixmap, EGL_KHR_image, EGL_KHR_gl_texture_2D_image, 
    EGL_KHR_gl_texture_cubemap_image, EGL_KHR_gl_renderbuffer_image, 
    EGL_KHR_surfaceless_context, EGL_KHR_create_context, EGL_NOK_swap_region, 
    EGL_NOK_texture_from_pixmap, EGL_EXT_create_context_robustness, 
    EGL_EXT_image_dma_buf_import, EGL_NV_post_sub_buffer
EGL_CLIENT_APIS: OpenGL OpenGL_ES OpenGL_ES2 OpenGL_ES3 
GL_VERSION: OpenGL ES 3.0 Mesa 10.1.3
GL_RENDERER: Mesa DRI Intel(R) Bay Trail 
GL_EXTENSIONS:
    GL_EXT_blend_minmax, GL_EXT_multi_draw_arrays, 
    GL_EXT_texture_filter_anisotropic, GL_EXT_texture_compression_dxt1, 
    GL_EXT_texture_format_BGRA8888, GL_OES_compressed_ETC1_RGB8_texture, 
    GL_OES_depth24, GL_OES_element_index_uint, GL_OES_fbo_render_mipmap, 
    GL_OES_mapbuffer, GL_OES_rgb8_rgba8, GL_OES_standard_derivatives, 
    GL_OES_stencil8, GL_OES_texture_3D, GL_OES_texture_npot, 
    GL_OES_EGL_image, GL_OES_depth_texture, GL_OES_packed_depth_stencil, 
    GL_EXT_texture_type_2_10_10_10_REV, GL_OES_get_program_binary, 
    GL_APPLE_texture_max_level, GL_EXT_discard_framebuffer, 
    GL_EXT_read_format_bgra, GL_NV_fbo_color_attachments, 
    GL_OES_EGL_image_external, GL_OES_vertex_array_object, 
    GL_ANGLE_texture_compression_dxt3, GL_ANGLE_texture_compression_dxt5, 
    GL_EXT_texture_rg, GL_EXT_unpack_subimage, GL_NV_draw_buffers, 
    GL_NV_read_buffer, GL_EXT_map_buffer_range, GL_OES_depth_texture_cube_map, 
    GL_OES_surfaceless_context, GL_EXT_color_buffer_float, 
    GL_EXT_shader_integer_mix
~~~

Logs of crash (including the trace as a base 64 encoded file): https://gist.github.com/sstewartgallus/73bcc0c0a6ee5e729f7e

**Comment by jrfonseca** [comment] 2015-01-02 15:02
> Okay so the issue appears to be that apitrace's eglGetProcAddress does not support querying for core functions while Mesa's does 

Apitrace actually supports that.  All functions that are obtained via `eglGetProcAddress()`, regardless being extensions or not, are intercepted just fine. The problem is a bit deeper..

The problem here is that `libGLESv2.so` is never loaded:

* the application doesn't depend on it nor does it `dlopen()` it

* `libEGL.so` also doesn't depend or load it (it gets its symbols from `libglapi.so`) 

So when apitrace needs to resolve GL entry-points for internal purposes, entry-points that the application never requested, like `dlsym(RTLD_NEXT, "glGetIntegerv")` will fail.

I'll push a fix for this shortly.  And with it I can trace you example app just fine.

> it would be nice if eglGetProcAddress did support querying for core functions the standard doesn't explicitly allow it

Actually, there is a  `EGL_KHR_get_all_proc_addresses` extension, and your app should query for it, before attempting to call `eglGetProcAddress()` on core symbols.  Mesa didn't support `EGL_KHR_get_all_proc_addresses` until recently, but I believe future releases will, as it is already in master branch.

By the way, your application calls `eglGetProcAddress()` before `eglInitialize()`. I'm not sure what the EGL specs say about that, but it sounds a tad dangerous at first glance.

> Your suggested patch does not actually seem to fix the problem but whatever.

Not sure what you mean here with "whatever".

**Closed** 2015-01-02 15:04 UTC
Labels: Tracing

**Comment by jrfonseca** [comment] 2015-01-02 15:06
> Mesa didn't support `EGL_KHR_get_all_proc_addresses` until recently,

I mean't Mesa didn't *advertise* `EGL_KHR_get_all_proc_addresses` until recently. It supports it fine, as you noticed.
